// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.School.Infrastructure.Persistent;

#nullable disable

namespace Modules.School.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260226081508_RemovePolicyType")]
    partial class RemovePolicyType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.School.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            CityId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Karkh"
                        },
                        new
                        {
                            Id = new Guid("b0000002-0000-0000-0000-000000000002"),
                            CityId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rusafa"
                        },
                        new
                        {
                            Id = new Guid("b0000003-0000-0000-0000-000000000003"),
                            CityId = new Guid("a0000002-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Al-Fao"
                        },
                        new
                        {
                            Id = new Guid("b0000004-0000-0000-0000-000000000004"),
                            CityId = new Guid("a0000002-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Shatt Al-Arab"
                        },
                        new
                        {
                            Id = new Guid("b0000005-0000-0000-0000-000000000005"),
                            CityId = new Guid("a0000003-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Old City"
                        },
                        new
                        {
                            Id = new Guid("b0000006-0000-0000-0000-000000000006"),
                            CityId = new Guid("a0000003-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nineveh Plains"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Baghdad"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Basra"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mosul"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000004"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Erbil"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000005"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kirkuk"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sanitizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12112121-2121-2121-2121-121212121212"),
                            Description = "This policy applies to all schools by default.",
                            IsActive = true,
                            IsDefault = true,
                            IsDeleted = false,
                            Title = "Master Policy",
                            sanitizeName = "master-policy"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sanitizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.Area", b =>
                {
                    b.HasOne("Modules.School.Domain.Entities.Place.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.City", b =>
                {
                    b.HasOne("Modules.School.Domain.Entities.Place.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.School", b =>
                {
                    b.HasOne("Modules.School.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modules.School.Domain.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Policy");
                });
#pragma warning restore 612, 618
        }
    }
}
