// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.School.Infrastructure.Persistent;

#nullable disable

namespace Modules.School.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260227080439_AddLanguageSeeds")]
    partial class AddLanguageSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.School.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            Code = "en",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("d0000002-0000-0000-0000-000000000002"),
                            Code = "ar",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = new Guid("d0000003-0000-0000-0000-000000000003"),
                            Code = "fr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("d0000004-0000-0000-0000-000000000004"),
                            Code = "es",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("d0000005-0000-0000-0000-000000000005"),
                            Code = "zh",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chinese (Mandarin)"
                        },
                        new
                        {
                            Id = new Guid("d0000006-0000-0000-0000-000000000006"),
                            Code = "hi",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = new Guid("d0000007-0000-0000-0000-000000000007"),
                            Code = "pt",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("d0000008-0000-0000-0000-000000000008"),
                            Code = "bn",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bengali"
                        },
                        new
                        {
                            Id = new Guid("d0000009-0000-0000-0000-000000000009"),
                            Code = "ru",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("d000000a-0000-0000-0000-00000000000a"),
                            Code = "ja",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("d000000b-0000-0000-0000-00000000000b"),
                            Code = "de",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("d000000c-0000-0000-0000-00000000000c"),
                            Code = "ko",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Korean"
                        },
                        new
                        {
                            Id = new Guid("d000000d-0000-0000-0000-00000000000d"),
                            Code = "it",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = new Guid("d000000e-0000-0000-0000-00000000000e"),
                            Code = "tr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = new Guid("d000000f-0000-0000-0000-00000000000f"),
                            Code = "vi",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = new Guid("d0000010-0000-0000-0000-000000000010"),
                            Code = "fa",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Persian"
                        },
                        new
                        {
                            Id = new Guid("d0000011-0000-0000-0000-000000000011"),
                            Code = "ur",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Urdu"
                        },
                        new
                        {
                            Id = new Guid("d0000012-0000-0000-0000-000000000012"),
                            Code = "id",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Indonesian"
                        },
                        new
                        {
                            Id = new Guid("d0000013-0000-0000-0000-000000000013"),
                            Code = "nl",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = new Guid("d0000014-0000-0000-0000-000000000014"),
                            Code = "pl",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Polish"
                        },
                        new
                        {
                            Id = new Guid("d0000015-0000-0000-0000-000000000015"),
                            Code = "th",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Thai"
                        },
                        new
                        {
                            Id = new Guid("d0000016-0000-0000-0000-000000000016"),
                            Code = "el",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Greek"
                        },
                        new
                        {
                            Id = new Guid("d0000017-0000-0000-0000-000000000017"),
                            Code = "sv",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Swedish"
                        },
                        new
                        {
                            Id = new Guid("d0000018-0000-0000-0000-000000000018"),
                            Code = "ro",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Romanian"
                        },
                        new
                        {
                            Id = new Guid("d0000019-0000-0000-0000-000000000019"),
                            Code = "cs",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Czech"
                        },
                        new
                        {
                            Id = new Guid("d000001a-0000-0000-0000-00000000001a"),
                            Code = "hu",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hungarian"
                        },
                        new
                        {
                            Id = new Guid("d000001b-0000-0000-0000-00000000001b"),
                            Code = "he",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hebrew"
                        },
                        new
                        {
                            Id = new Guid("d000001c-0000-0000-0000-00000000001c"),
                            Code = "uk",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Id = new Guid("d000001d-0000-0000-0000-00000000001d"),
                            Code = "ms",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Malay"
                        },
                        new
                        {
                            Id = new Guid("d000001e-0000-0000-0000-00000000001e"),
                            Code = "sw",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Swahili"
                        },
                        new
                        {
                            Id = new Guid("d000001f-0000-0000-0000-00000000001f"),
                            Code = "ta",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = new Guid("d0000020-0000-0000-0000-000000000020"),
                            Code = "ku",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kurdish"
                        },
                        new
                        {
                            Id = new Guid("d0000021-0000-0000-0000-000000000021"),
                            Code = "da",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Danish"
                        },
                        new
                        {
                            Id = new Guid("d0000022-0000-0000-0000-000000000022"),
                            Code = "no",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Norwegian"
                        },
                        new
                        {
                            Id = new Guid("d0000023-0000-0000-0000-000000000023"),
                            Code = "fi",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Finnish"
                        },
                        new
                        {
                            Id = new Guid("d0000024-0000-0000-0000-000000000024"),
                            Code = "sk",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Slovak"
                        },
                        new
                        {
                            Id = new Guid("d0000025-0000-0000-0000-000000000025"),
                            Code = "bg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bulgarian"
                        },
                        new
                        {
                            Id = new Guid("d0000026-0000-0000-0000-000000000026"),
                            Code = "hr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Croatian"
                        },
                        new
                        {
                            Id = new Guid("d0000027-0000-0000-0000-000000000027"),
                            Code = "sr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Serbian"
                        },
                        new
                        {
                            Id = new Guid("d0000028-0000-0000-0000-000000000028"),
                            Code = "ca",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Catalan"
                        },
                        new
                        {
                            Id = new Guid("d0000029-0000-0000-0000-000000000029"),
                            Code = "af",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Afrikaans"
                        },
                        new
                        {
                            Id = new Guid("d000002a-0000-0000-0000-00000000002a"),
                            Code = "ne",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nepali"
                        },
                        new
                        {
                            Id = new Guid("d000002b-0000-0000-0000-00000000002b"),
                            Code = "si",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sinhala"
                        },
                        new
                        {
                            Id = new Guid("d000002c-0000-0000-0000-00000000002c"),
                            Code = "mr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = new Guid("d000002d-0000-0000-0000-00000000002d"),
                            Code = "pa",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Punjabi"
                        },
                        new
                        {
                            Id = new Guid("d000002e-0000-0000-0000-00000000002e"),
                            Code = "gu",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gujarati"
                        },
                        new
                        {
                            Id = new Guid("d000002f-0000-0000-0000-00000000002f"),
                            Code = "am",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Amharic"
                        },
                        new
                        {
                            Id = new Guid("d0000030-0000-0000-0000-000000000030"),
                            Code = "ha",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hausa"
                        },
                        new
                        {
                            Id = new Guid("d0000031-0000-0000-0000-000000000031"),
                            Code = "yo",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yoruba"
                        },
                        new
                        {
                            Id = new Guid("d0000032-0000-0000-0000-000000000032"),
                            Code = "so",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Somali"
                        },
                        new
                        {
                            Id = new Guid("d0000033-0000-0000-0000-000000000033"),
                            Code = "lt",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lithuanian"
                        },
                        new
                        {
                            Id = new Guid("d0000034-0000-0000-0000-000000000034"),
                            Code = "lv",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Latvian"
                        },
                        new
                        {
                            Id = new Guid("d0000035-0000-0000-0000-000000000035"),
                            Code = "et",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Estonian"
                        },
                        new
                        {
                            Id = new Guid("d0000036-0000-0000-0000-000000000036"),
                            Code = "sl",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Slovenian"
                        },
                        new
                        {
                            Id = new Guid("d0000037-0000-0000-0000-000000000037"),
                            Code = "sq",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Albanian"
                        },
                        new
                        {
                            Id = new Guid("d0000038-0000-0000-0000-000000000038"),
                            Code = "mk",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Macedonian"
                        },
                        new
                        {
                            Id = new Guid("d0000039-0000-0000-0000-000000000039"),
                            Code = "hy",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Armenian"
                        },
                        new
                        {
                            Id = new Guid("d000003a-0000-0000-0000-00000000003a"),
                            Code = "ka",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Georgian"
                        },
                        new
                        {
                            Id = new Guid("d000003b-0000-0000-0000-00000000003b"),
                            Code = "kk",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kazakh"
                        },
                        new
                        {
                            Id = new Guid("d000003c-0000-0000-0000-00000000003c"),
                            Code = "uz",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Uzbek"
                        },
                        new
                        {
                            Id = new Guid("d000003d-0000-0000-0000-00000000003d"),
                            Code = "az",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            Id = new Guid("d000003e-0000-0000-0000-00000000003e"),
                            Code = "ky",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kyrgyz"
                        },
                        new
                        {
                            Id = new Guid("d000003f-0000-0000-0000-00000000003f"),
                            Code = "tk",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Turkmen"
                        },
                        new
                        {
                            Id = new Guid("d0000040-0000-0000-0000-000000000040"),
                            Code = "tg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tajik"
                        },
                        new
                        {
                            Id = new Guid("d0000041-0000-0000-0000-000000000041"),
                            Code = "mn",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mongolian"
                        },
                        new
                        {
                            Id = new Guid("d0000042-0000-0000-0000-000000000042"),
                            Code = "my",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Burmese"
                        },
                        new
                        {
                            Id = new Guid("d0000043-0000-0000-0000-000000000043"),
                            Code = "km",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Khmer"
                        },
                        new
                        {
                            Id = new Guid("d0000044-0000-0000-0000-000000000044"),
                            Code = "lo",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lao"
                        },
                        new
                        {
                            Id = new Guid("d0000045-0000-0000-0000-000000000045"),
                            Code = "tl",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tagalog"
                        },
                        new
                        {
                            Id = new Guid("d0000046-0000-0000-0000-000000000046"),
                            Code = "is",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Icelandic"
                        },
                        new
                        {
                            Id = new Guid("d0000047-0000-0000-0000-000000000047"),
                            Code = "mt",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maltese"
                        },
                        new
                        {
                            Id = new Guid("d0000048-0000-0000-0000-000000000048"),
                            Code = "cy",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Welsh"
                        },
                        new
                        {
                            Id = new Guid("d0000049-0000-0000-0000-000000000049"),
                            Code = "ga",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Irish"
                        },
                        new
                        {
                            Id = new Guid("d000004a-0000-0000-0000-00000000004a"),
                            Code = "gd",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Scottish Gaelic"
                        },
                        new
                        {
                            Id = new Guid("d000004b-0000-0000-0000-00000000004b"),
                            Code = "eu",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Basque"
                        },
                        new
                        {
                            Id = new Guid("d000004c-0000-0000-0000-00000000004c"),
                            Code = "gl",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Galician"
                        },
                        new
                        {
                            Id = new Guid("d000004d-0000-0000-0000-00000000004d"),
                            Code = "bs",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bosnian"
                        },
                        new
                        {
                            Id = new Guid("d000004e-0000-0000-0000-00000000004e"),
                            Code = "lb",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Luxembourgish"
                        },
                        new
                        {
                            Id = new Guid("d000004f-0000-0000-0000-00000000004f"),
                            Code = "ps",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = new Guid("d0000050-0000-0000-0000-000000000050"),
                            Code = "sd",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sindhi"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            CityId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Karkh"
                        },
                        new
                        {
                            Id = new Guid("b0000002-0000-0000-0000-000000000002"),
                            CityId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rusafa"
                        },
                        new
                        {
                            Id = new Guid("b0000003-0000-0000-0000-000000000003"),
                            CityId = new Guid("a0000002-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Al-Fao"
                        },
                        new
                        {
                            Id = new Guid("b0000004-0000-0000-0000-000000000004"),
                            CityId = new Guid("a0000002-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Shatt Al-Arab"
                        },
                        new
                        {
                            Id = new Guid("b0000005-0000-0000-0000-000000000005"),
                            CityId = new Guid("a0000003-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Old City"
                        },
                        new
                        {
                            Id = new Guid("b0000006-0000-0000-0000-000000000006"),
                            CityId = new Guid("a0000003-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nineveh Plains"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Baghdad"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Basra"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mosul"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000004"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Erbil"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000005"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kirkuk"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sanitizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12112121-2121-2121-2121-121212121212"),
                            Description = "This policy defines the general operational and behavioral guidelines applicable to all schools unless otherwise specified.",
                            IsActive = true,
                            IsDefault = true,
                            IsDeleted = false,
                            Title = "General School Policy",
                            sanitizeName = "general-school-policy"
                        });
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sanitizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.Area", b =>
                {
                    b.HasOne("Modules.School.Domain.Entities.Place.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.Place.City", b =>
                {
                    b.HasOne("Modules.School.Domain.Entities.Place.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Modules.School.Domain.Entities.School", b =>
                {
                    b.HasOne("Modules.School.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modules.School.Domain.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Policy");
                });
#pragma warning restore 612, 618
        }
    }
}
